### ISSUE TITLE
Gesture recognizer does not run on the emulator

### ISSUE THREAD

**Issue by ikalkavouris** [google-ai-edge/mediapipe-samples#417]
And this is the exception:

```
FATAL EXCEPTION: pool-2-thread-1
                                                                                                    Process: com.google.mediapipe.examples.gesturerecognizer, PID: 17828
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_tasks_vision_jni.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.google.mediapipe.tasks.vision.gesturerecognizer.GestureRecognizer.<clinit>(GestureRecognizer.java:97)
                                                                                                    	at com.google.mediapipe.examples.gesturerecognizer.GestureRecognizerHelper.setupGestureRecognizer(GestureRecognizerHelper.kt:95)
                                                                                                    	at com.google.mediapipe.examples.gesturerecognizer.GestureRecognizerHelper.<init>(GestureRecognizerHelper.kt:50)
                                                                                                    	at com.google.mediapipe.examples.gesturerecognizer.fragment.CameraFragment.onViewCreated$lambda-4(CameraFragment.kt:147)
                                                                                                    	at com.google.mediapipe.examples.gesturerecognizer.fragment.CameraFragment.$r8$lambda$xiZI6LDAjMBw-J7vyrjSe_CLWo0(Unknown Source:0)
                                                                                                    	at com.google.mediapipe.examples.gesturerecognizer.fragment.CameraFragment$$ExternalSyntheticLambda13.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

Android Studio Iguana | 2023.2.1 Patch 2

**Comment by PaulTR** [comment]
Correct, vision tasks, due to hardware requirements in the SDK, will not work in the emulator.
